### ISSUE TITLE
RiTa is not defined error when passing "nns" as "pos"

### ISSUE THREAD

**Issue by calebfoss** [dhowe/ritajs#124]
I am only seeing this issue on node js, not when running in the browser.
Steps to reproduce:
`const rita = require("rita");
rita.randomWord({ pos: "nns" }));`
Throws this error:
`ReferenceError: RiTa is not defined
    at n.exports.matchPos (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/rita/2.4.1/node_modules/rita/dist/rita.js:5:62645)
    at n.exports.randomWord (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/rita/2.4.1/node_modules/rita/dist/rita.js:5:60249)
    at Function.randomWord (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/rita/2.4.1/node_modules/rita/dist/rita.js:5:39670)
    at /app/server.js:6:22
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/8663596e-bb62-437e-9454-fc8232fbdb46/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)`

**Comment by dhowe** [comment]
Hi @calebfoss sorry I've only just seen this (not sure how I missed the notification). Anyhow, it seems to be working now:

```
$ cat index.js 
let RiTa = require('rita');
console.log(RiTa.VERSION);
console.log(RiTa.randomWord({ pos: "nns" }));

$ node index.js 
2.4.70
vowels
```

Do you mind giving it a test (and closing this if its ok)?
