### ISSUE TITLE
[Riscript] Should resolve functions on context symbols

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/ritajs#157]
The test sometime fails (not very common, but for now seems already appear twice in PR CI tests including #156...)

see `riscript-tests.js line 1180`

https://github.com/dhowe/ritajs/blob/b2ee27454b1ffa5c88f0115c505d3dd4da09f58d/test/riscript-tests.js#L1180

**Comment by dhowe** [comment]
yes, I've noticed this as well - pls add the error message if you can

**Comment by Real-John-Cheung** [comment]
Here is the logs
```
Error: [@9,24:28='.secs',<21>,1:24] line 1, col 24: mismatched input '.secs' expecting MDS

      at a.value (dist/rita.js:5:956131)

      at /Users/runner/work/ritajs/ritajs/dist/rita.js:1:43490

      at Array.map (<anonymous>)

      at ProxyErrorListener.syntaxError (dist/rita.js:1:43481)

      at a.notifyErrorListeners (dist/rita.js:5:39482)

      at d.reportInputMismatch (dist/rita.js:1:48425)

      at d.reportError (dist/rita.js:1:46665)

      at a.value (dist/rita.js:5:918743)

      at a.value (dist/rita.js:5:909954)

      at a.value (dist/rita.js:5:909165)

      at a.value (dist/rita.js:5:908230)

      at n.value (dist/rita.js:5:957900)

      at n.value (dist/rita.js:5:958122)

      at n.value (dist/rita.js:5:958479)

      at n.value (dist/rita.js:5:956594)

      at Function.value (dist/rita.js:5:959484)

      at Proxy.value (dist/rita.js:5:1264200)

      at Context.<anonymous> (test/riscript-tests.js:1193:22)

      at processImmediate (internal/timers.js:462:21)
```

**Comment by dhowe** [comment]
This is happening somewhat regularly:

```
RiTa.RiScript
       Transform
         Should resolve functions on context symbols:
     Error: [@9,24:28='.secs',<21>,1:24] line 1, col 24: mismatched input '.secs' expecting MDS
```
